# Generated by Django 3.0.4 on 2020-04-03 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('tags', models.CharField(choices=[('Other Electronics', 'Other Electronics'), ('Laptops', 'Laptops'), ('PC', 'PC'), ('Tablets', 'Tablets'), ('Mobiles', 'Mobiles'), ('Clothes', 'Clothes'), ('Automotives', 'Automotives'), ('Furniture', 'Furniture')], default='Undefined', max_length=20)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('price', models.PositiveIntegerField(default=100)),
                ('image', models.ImageField(upload_to='ad-photos')),
                ('slug', models.SlugField(unique=True)),
                ('sold', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Advert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
