# Generated by Django 3.0.4 on 2020-04-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200402_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defaults/avatar.png', upload_to='profile_pics/'),
        ),
    ]
